### ISSUE TITLE
Why are we not using default exports?

### ISSUE THREAD

**Issue by wagenet** [Gavant/glint-template-types#6]
Since each has its own file, why have:

```ts
import { FaIconComponent } from '@gavant/glint-template-types/types/@fortawesome/ember-fontawesome/fa-icon';
```

and not

```ts
import FaIconComponent from '@gavant/glint-template-types/types/@fortawesome/ember-fontawesome/fa-icon';
```

**Comment by bakerac4** [comment]
The main reason I use named exports as a pattern is to make it easily discoverable in VScode for autocompletion. But we could also use both because Im not particularly tied to a certain direction for this package

**Comment by wagenet** [comment]
Just realized I may have broken things in the ember-render-modifiers change. I'll submit a fix soon. Just don't release until I do :)

**Comment by bakerac4** [comment]
Haha, no problem. I'll probably wait to release until you add everything you want to anyways 😄

**Comment by wagenet** [comment]
@bakerac4 if you do `export default Foo` then VSCode picks it up as `Foo`.
