### ISSUE TITLE
Dependency tree error for 0.3.5

### ISSUE THREAD

**Issue by barryofguilder** [Gavant/glint-template-types#81]
I'm currently using 0.3.4 of this package. When I try to install 0.3.5, I get the following dependency tree error:

<img width="966" alt="Screenshot 2023-08-17 at 3 30 31 PM" src="https://github.com/Gavant/glint-template-types/assets/5649106/0b5da2dc-747e-4983-ac47-e1d2f395247b">

I have "~4.12.3" for`ember-source` in my app, so I'm not sure why I get the error. If I go back and install 0.3.4, everything works.

**Comment by elidupuis** [comment]
I literally just hit this same issue

**Comment by bertdeblock** [comment]
The peer dep on `ember-source` isn't defined correctly. https://github.com/Gavant/glint-template-types/pull/84 should fix this.
